site_name: MLOps Project
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tracking  # Permet de suivre la section active
  hide:
    - navigation  # Masque complètement la barre de navigation


# nav:
#   - Accueil: index.md

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - md_in_html
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.highlight
  - md_in_html
  - footnotes
  - tables
  - admonition
  - toc:
      permalink: true
